on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code (2)
        uses: actions/checkout@v2


      - name: Install cc-test-reporter
        run: |
          curl -L 'https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64' > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Test
        run: go test -failfast -race ./...
 
      - name: Lint
        run: |
          go get golang.org/x/lint/golint
          golint -set_exit_status ./...

      - name: Vet
        run: go vet ./...
      
      - name: Test Coverage
        run: |
          ./cc-test-reporter before-build
          go test -covermode atomic -coverprofile=c.out ./...
          ./cc-test-reporter after-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
