on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -failfast -race -covermode atomic -coverprofile=c.out ./...
 
      - name: Lint
        run: |
          go get golang.org/x/lint/golint
          golint -set_exit_status ./...

      - name: Vet
        run: go vet ./...
        
#      - name: Install goveralls
#        env:
#          GO111MODULE: off
#        run: go get github.com/mattn/goveralls
      
      - name: Test Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}

#      - name: Send coverage
#        env:
#          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: goveralls -coverprofile=covprofile -service=github -ignore='examples'

